apiVersion: v1
kind: ConfigMap
metadata:
    name: tsig-secret
data:
    tsig_secret.yaml: ENC[AES256_GCM,data:59rLzqOpSVIVYkvP8YanzcR1vcjbM84xeOT3YbsOfrQzOYdh5iFJnZXHLA6Rayao8dGbdWRMVllq+IiKY/zgirHF+S91RPajJUaXU/kfS/4LVluqk53vA5ZyeA1yDHsaecBn9KejZe6z/7kj53ZSE84/qDMpSLxDbpnywZlfcZVl5b5zOhmHIcfcebnZXQFeK//VZTjOYZxBXUhSpdphKWKXKUxEVaRBTVN3wNxUpAXmJHYBj0iF/pZpMQ+FU7S0xLgl8Hr1WFYxGh01Pqhz9I0/JAiB8HgbvymylSjWbF6fRek7RuhrN9yqJcbLpY7r,iv:AtD7LuXkCXqdxx/wNnMp9amwPTuC2KkAJ5F4xal4jh8=,tag:Ml4yR+TEu1zjm4QmDFut8A==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2025-05-20T09:22:40Z"
    mac: ENC[AES256_GCM,data:f0aZPsk0pl5KoQidPs8iQvRAMm2/2GrQ2PZvMCQNTYjWezodC0qiIbY/Uu162330aXpOABLSGDBp0J/A4UF21TLQMKTE9knDoStZskaG1Sc8AF/fShteBQbCNjWclG5vFgWNQmdpnFmC5mf++MUXyvL/a2jF5gOGMi461Vi/hYc=,iv:dY5Ry5rqxhdcRvBVRA3rmZoZ4yU0vC/IUIphWhhe5p8=,tag:+f9h48R5XkVn2HluOrxoWQ==,type:str]
    pgp:
        - created_at: "2025-05-20T09:22:40Z"
          enc: "-----BEGIN PGP MESSAGE-----\r\n\r\nhQIMAwCh9W6WSzWFAQ/8Dy1E7+/ybjTVb9P80+9rDZMB7QS7bueUS6UyZAIHpYDe\r\nDuA8jSL1HusRy5zOnb1spVakdunSQeOo8juibe3I+rx+591DNOqEZzMuIGBTyiV8\r\nTxHTq6DpViKwLyAHP/08d63mWejd33VwtTZSpuzZGjsI6ZxLuIbm9VKeF0MZ1sC4\r\nX7RdrFFxCtLTMBuXLU6gZIlWa0z1+5PCA6EiEbljExeprpwBNlf4TaAPuYDxRZbT\r\nhmXNlzG1MgRc6fFnHepd6TgqbMymPuDlFAv+hIVqTDaHmuYCFVOLLUSqNI5LGMtO\r\noZjVH44Md0Ee2QufkPx1LNKyClSpGq93gL6LVxJYh4hJHLd2J8QRAm+Xh9rSXbbZ\r\nndhocxVY6y7YQcnFlAe0dGLivmvgHXWzFE5OCobcVqMyFmpjI0dicDZ8NW4Blyl9\r\nICxG1q/xP6404Wwk6OZLxgbkOaGFg8PP4aTth6xEAz7QwBrt4cNQahZRou8zmFBJ\r\nOPICT+cJSNzj+gvEOOPWOhBvDYqqC4IPuDC3sRt5nAZsnw5Jgqmgahm+iVhQW/KG\r\nzE1NGZmrgG2RfuEwTl/4jFRkkaYKOOyq2b0PMVY4VaTrbkFWEZkuGIzGxd1C/Un3\r\n34yFFjeTjhZRSkRO8YIfwTXZ8CGBKPRU2MUECsCWTXTUukK5QlPHo1o2Uu8JwnTS\r\nXAG0TrR90P1F95IZXeH18GjMljyG+jbQEyWw53e7gUabqYyueZVRWqoY3sh+FBlf\r\nhyA82fi77NvEKdBxMwFDOQml1hwQZSi6LibbczeOG3AgpYLiaHhi+L90kt3p\r\n=wnEF\r\n-----END PGP MESSAGE-----"
          fp: 0C428B22CE2BBFD2D7B81A4D5E85BCA244CB53A5
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
