apiVersion: v1
kind: ConfigMap
metadata:
  name: mongodb-cluster
  namespace: soris-stage
data:
  namespace-mongodb-cluster.yaml: |
    apiVersion: v1
    kind: Namespace
    metadata:
      name: mongodb
  mongodb-cluster.yaml: |
    apiVersion: psmdb.percona.com/v1
    kind: PerconaServerMongoDB
    metadata:
      name: soris-mongo-psmdb-db
      namespace: mongodb
    spec:
      clusterServiceDNSSuffix: svc.soris-stage-citymat.local
      backup:
        enabled: false
        image: percona/percona-backup-mongodb:2.7.0-multi
        pitr: {enabled: false}
      crVersion: 1.18.0
        
      image: percona/percona-server-mongodb:6.0.21-18
      imagePullPolicy: Always
      replsets:
      - arbiter:
          enabled: false
          size: 1
        expose: 
          enabled: true
          type: ClusterIP
          annotations:
            metallb.io/loadBalancerIPs: 10.10.119.153
            metallb.io/allow-shared-ip: "key-to-share-1.2.3.4"
        name: rs0
        resources:
          limits: {cpu: 600m, memory: 1G}
          requests: {cpu: 600m, memory: 1G}
        size: 3
        volumeSpec:
          persistentVolumeClaim:
            resources:
              requests: {storage: 10Gi}
            storageClassName: sc-ent-plus
      secrets: {users: soris-mongo-psmdb-db-secrets}
      sharding:
        balancer: {enabled: true}
        configsvrReplSet:
          resources:
            limits: {cpu: 600m, memory: 1G}
            requests: {cpu: 600m, memory: 1G}
          size: 3
          volumeSpec:
            persistentVolumeClaim:
              resources:
                requests: {storage: 10Gi}
              storageClassName: sc-ent-plus
        enabled: true
        mongos:
          expose:
            type: LoadBalancer
            annotations:
              metallb.io/loadBalancerIPs: 10.10.119.153
              metallb.io/allow-shared-ip: "key-to-share-1.2.3.4" 
          resources:
            limits: {cpu: 600m, memory: 1G}
            requests: {cpu: 600m, memory: 1G}
          size: 2
  mongodb-dev-cluster.yaml: |
    apiVersion: psmdb.percona.com/v1
    kind: PerconaServerMongoDB
    metadata:
      name: soris-mongo-psmdb-db
      namespace: mongodb-dev
    spec:
      clusterServiceDNSSuffix: svc.soris-stage-citymat.local
      backup:
        enabled: false
        image: percona/percona-backup-mongodb:2.7.0-multi
        pitr: {enabled: false}
      crVersion: 1.18.0
        
      image: percona/percona-server-mongodb:6.0.21-18
      imagePullPolicy: Always
      replsets:
      - arbiter:
          enabled: false
          size: 1
        expose: 
          enabled: true
          type: ClusterIP
        name: rs0
        resources:
          limits: {cpu: 600m, memory: 1G}
          requests: {cpu: 600m, memory: 1G}
        size: 3
        volumeSpec:
          persistentVolumeClaim:
            resources:
              requests: {storage: 10Gi}
            storageClassName: sc-ent-plus
      secrets: {users: soris-mongo-psmdb-db-secrets}
      sharding:
        balancer: {enabled: true}
        configsvrReplSet:
          resources:
            limits: {cpu: 600m, memory: 1G}
            requests: {cpu: 600m, memory: 1G}
          size: 3
          volumeSpec:
            persistentVolumeClaim:
              resources:
                requests: {storage: 10Gi}
              storageClassName: sc-ent-plus
        enabled: true
        mongos:
          expose:
            type: LoadBalancer
            annotations:
              metallb.io/loadBalancerIPs: 10.10.119.154
              metallb.io/allow-shared-ip: "key-to-share-1.2.3.5" 
          resources:
            limits: {cpu: 600m, memory: 1G}
            requests: {cpu: 600m, memory: 1G}
          size: 2
          
---
apiVersion: config.projectsveltos.io/v1beta1
kind: Profile
metadata:
  name: mongodb-cluster-soris
  namespace: soris-stage
spec:
  clusterSelector:
    matchLabels:
      mongodb-cluster: soris
  syncMode: ContinuousWithDriftDetection
  policyRefs:
    - name: mongodb-cluster
      namespace: soris-stage
      kind: ConfigMap
    - name: mongodb-cluster-secrets
      namespace: soris-stage
      kind: ConfigMap
