apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - profile.yaml
  - secrets/tsig-secret.yaml

configMapGenerator:
- name: dinova-letsencypt-cmap
  namespace: soris-stage

  files:
  - cluster-issuer.yaml=dinova-letsencrypt.yaml
generatorOptions:
  disableNameSuffixHash: true