apiVersion: config.projectsveltos.io/v1beta1
kind: Profile
metadata:
  name: scdf-dev-profile
  namespace: soris-stage
spec:
  dependsOn:
    - scdf-dev-dbs-profile
  clusterSelector:
    matchLabels:
      scdf-dev: scdf
  syncMode: ContinuousWithDriftDetection
  helmCharts:
    - repositoryURL: oci://registry-1.docker.io/bitnamicharts
      repositoryName: scdf
      chartName: spring-cloud-dataflow
      chartVersion: 37.0.4
      releaseName: scdf-dev
      releaseNamespace: scdf-dev
      helmChartAction: Install
      values: |
        mariadb:
          enabled: false
        
        externalDatabase:
          driver: org.postgresql.Driver
          hibernateDialect: 'org.hibernate.dialect.PostgreSQLDialect'
          host: 'postgresql-citymat-rw.postgresql.svc'
          port: 5432
          scheme: postgresql
          dataflow:
            database: dataflow-dev
            username: 'soris-scdf-dev'
            existingSecret: 'soris-scdf-dev-user'
            existingSecretPasswordKey: "password"
          skipper:
            database: skipper-dev
            username: 'soris-scdf-dev'
            existingSecret: 'soris-scdf-dev-user'
            existingSecretPasswordKey: "password"
        
        rabbitmq:
          enabled: false
        
        externalKafka:
          enabled: true
          brokers: 'jhipster-kafka-brokers.kafka-dev.svc:9092'
        
        clusterDomain: 'soris-stage-citymat.local'
        
        server:
          networkPolicy:
            extraEgress:
              - port: 7577
                protocol: TCP
            enabled: false
          extraEnvVars:
            - name: SPRING_DATASOURCE_HIKARI_MAXIMUM-POOL-SIZE
              value: "15"
            - name: SPRING_DATASOURCE_HIKARI_MINIMUM-IDLE
              value: "10"
            - name: SPRING_DATASOURCE_HIKARI_IDLE-TIMEOUT
              value: "300000"
          ingress:
            enabled: true
            ingressClassName: nginx-management
            hostname: scdf-dev.soris-stage.k8s.dinova.services
            annotations:
              cert-manager.io/cluster-issuer: dinova-letsencrypt
              external-dns.alpha.kubernetes.io/target: mgmt.soris-stage.k8s.dinova.services
            tls: true
        
        metrics:
          resourcesPreset: "small"
          startupProbe:
            enabled: true
            initialDelaySeconds: 60
            periodSeconds: 30
            timeoutSeconds: 5
            successThreshold: 1
            failureThreshold: 10
          livenessProbe:
            enabled: true
            initialDelaySeconds: 60
            periodSeconds: 30
            timeoutSeconds: 5
            successThreshold: 1
            failureThreshold: 10  
          readinessProbe:
            enabled: true
            initialDelaySeconds: 60
            periodSeconds: 30
            timeoutSeconds: 5
            successThreshold: 1
            failureThreshold: 10
        
          networkPolicy:
            enabled: false
          enabled: true
          serviceMonitor:
            enabled: true
        
        skipper:
          networkPolicy:
            enabled: false
          extraEnvVars:
            - name: SPRING_DATASOURCE_HIKARI_MAXIMUM-POOL-SIZE
              value: "10"
            - name: SPRING_DATASOURCE_HIKARI_MINIMUM-IDLE
              value: "5"
            - name: SPRING_DATASOURCE_HIKARI_IDLE-TIMEOUT
              value: "300000"

  policyRefs:
    - name: scdf-dev-scrapeconfigs
      kind: ConfigMap
    - name: scdf-dev-psql-svc
      kind: ConfigMap
