apiVersion: v1
kind: ConfigMap
metadata:
  name: nfs-sc
  namespace: soris-stage
data:
  nfs-sc.yaml: |
    apiVersion: storage.k8s.io/v1
    kind: StorageClass
    metadata:
      name: nfs-sc
    provisioner: nfs.csi.k8s.io
    parameters:
      server: 10.10.119.10
      share: /nfsdata
    reclaimPolicy: Delete
    mountOptions:
      - nfsvers=4.1
    allowVolumeExpansion: true
    volumeBindingMode: Immediate
