apiVersion: v1
kind: ConfigMap
metadata:
  name: nfs-csi-driver
  namespace: soris-stage
data:
  # the following CSIDriver prevents Kubernetes from attempting to change permissions on NFS volumes
  csi-driver.yaml: |
    apiVersion: storage.k8s.io/v1
    kind: CSIDriver
    metadata:
      name: nfs.csi.k8s.io
    spec:
      fsGroupPolicy: None

