apiVersion: helm.toolkit.fluxcd.io/v2
kind: ClastixParams
metadata:
  name: ${{ values.clustername }}
spec:
  contract: ${{ values.contract }}
  clustername: ${{ values.clustername }}
  clusterdomain: ${{ values.clusterdomain }}
  apiserverip: ${{ values.apiserverip }}
  cpreplicas: ${{ values.cpreplicas }}
  datastore: ${{ values.datastore }}
  k8sversion: ${{ values.k8sversion }}
  gatewayip: ${{ values.gatewayip }}

  dcname: ${{ values.dcname }}
  dcurl: ${{ values.dcurl }}
  dcthumbprint: ${{ values.dcthumbprint }}
  dccredsecret: ${{ values.dccredsecret }}
  dcfolder: ${{ values.dcnodefolder }}
  dcnodepool: ${{ values.dcnodepool }}
  dcstorage: ${{ values.dcnodestoragepolicy }}
  dcvmtemplate: ${{ values.dcnodevmtemplate }}
  dcnetwork: ${{ values.dcnodenetwork }}

  ipampool: 
{% for ranges in values.ipampoolranges %}
    - rangestart: ${{ ranges.rangestart }}
      rangeend: ${{ ranges.rangeend }}
      prefix: ${{ values.ipamrangeprefix }}
      gateway: ${{ values.ipamrangegw }}
      ipamname: ${{ values.ipampoolname }}
{% endfor %}
  nodesinfo: 
{%- for ninfo in values.nodeinfo %}
    - nodename: ${{ ninfo.nodename }}
      replicas: ${{ ninfo.replicas  }}
      cpu: ${{ ninfo.cpu }}
      mbram: ${{ ninfo.mbram }}
      gbdisk: ${{ ninfo.gbdisk }}
      nodetaints:
  {% for taint in ninfo.taints -%}
        - taintkey: ${{ taint.key }}
          taintvalue: ${{ taint.value }}
  {%- endfor -%}
        # -- Labels to add to the node pool when joining the cluster
      nodelabels:
  {% for label in ninfo.labels -%}
        - labelkey: ${{ label.key }}
          labelvalue: ${{ label.value }}
  {%- endfor -%}
      sveltosapps:
  {% for app in values.sveltosapps -%}
        - ${{ app }}
  {%- endfor -%}
{% endfor %}

