apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - profile.yaml
configMapGenerator:
  - name: sftpgo-pvc-share
    files:
      - share-pvc.yaml=share-pvc.yaml
generatorOptions:
    disableNameSuffixHash: true
