apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - profile.yaml
  - scdf-dbs-profile.yaml
  - secrets/db-user-secret.yaml
generatorOptions:
  disableNameSuffixHash: true
configMapGenerator:
  - name: scdf-test-dbs-profile
    namespace: soris-stage
    files:
      - db.yaml
  - name: scdf-test-scrapeconfigs
    namespace: soris-stage
    files:
      - scrapeconfigs.yaml=scrapeconfigs.yaml
  - name: scdf-test-psql-svc
    namespace: soris-stage
    files:
      - postgres-svc.yaml=postgres-svc.yaml
